-- ============================================================
-- SELLF - PostgreSQL / Neon
-- Conversão do dump MySQL para PostgreSQL
-- ============================================================

-- ============================================================
-- LIMPEZA
-- ============================================================

DROP TABLE IF EXISTS imagem_produto CASCADE;
DROP TABLE IF EXISTS anuncio CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS loja_anunciante CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS localizacao CASCADE;

DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS condicao_produto CASCADE;
DROP TABLE IF EXISTS status_anuncio CASCADE;
DROP TABLE IF EXISTS status_loja CASCADE;
DROP TABLE IF EXISTS status_usuario CASCADE;
DROP TABLE IF EXISTS tipo_usuario CASCADE;


-- ============================================================
-- TABELAS AUXILIARES
-- ============================================================

CREATE TABLE tipo_usuario (
    idtipo_usuario INTEGER PRIMARY KEY,
    tipo_usuario VARCHAR(45) NOT NULL
);

CREATE TABLE status_usuario (
    idstatus_usuario INTEGER PRIMARY KEY,
    status_usuario VARCHAR(45)
);

CREATE TABLE status_loja (
    idstatus_loja INTEGER PRIMARY KEY,
    status_loja VARCHAR(45)
);

CREATE TABLE status_anuncio (
    idstatus_anuncio INTEGER PRIMARY KEY,
    status_anuncio VARCHAR(45)
);

CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE condicao_produto (
    id_condicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);


-- ============================================================
-- LOCALIZAÇÃO
-- ============================================================

CREATE TABLE localizacao (
    id_localizacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade VARCHAR(100),
    estado VARCHAR(50),
    cep VARCHAR(45),
    bairro VARCHAR(100)
);


-- ============================================================
-- USUÁRIO
-- ============================================================

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14),
    telefone VARCHAR(20),
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idtipo_usuario INTEGER NOT NULL,
    idstatus_usuario INTEGER NOT NULL,
    id_localizacao INTEGER NOT NULL,
    senha_resetada SMALLINT DEFAULT 0,

    CONSTRAINT fk_usuario_tipo
        FOREIGN KEY (idtipo_usuario)
        REFERENCES tipo_usuario(idtipo_usuario),

    CONSTRAINT fk_usuario_status
        FOREIGN KEY (idstatus_usuario)
        REFERENCES status_usuario(idstatus_usuario),

    CONSTRAINT fk_usuario_localizacao
        FOREIGN KEY (id_localizacao)
        REFERENCES localizacao(id_localizacao)
);


-- ============================================================
-- LOJA
-- ============================================================

CREATE TABLE loja_anunciante (
    id_loja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    id_usuario INTEGER,
    id_localizacao INTEGER,
    idstatus_loja INTEGER NOT NULL,

    CONSTRAINT fk_loja_status
        FOREIGN KEY (idstatus_loja)
        REFERENCES status_loja(idstatus_loja),

    CONSTRAINT fk_loja_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_loja_localizacao
        FOREIGN KEY (id_localizacao)
        REFERENCES localizacao(id_localizacao)
);


-- ============================================================
-- PRODUTO
-- ============================================================

CREATE TABLE produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    preco VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'ativo',
    id_loja INTEGER,
    id_categoria INTEGER,
    id_condicao INTEGER,

    CONSTRAINT fk_produto_loja
        FOREIGN KEY (id_loja)
        REFERENCES loja_anunciante(id_loja),

    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria),

    CONSTRAINT fk_produto_condicao
        FOREIGN KEY (id_condicao)
        REFERENCES condicao_produto(id_condicao)
);


-- ============================================================
-- ANÚNCIO
-- ============================================================

CREATE TABLE anuncio (
    id_anuncio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT,
    id_produto INTEGER UNIQUE,
    idstatus_anuncio INTEGER NOT NULL,

    CONSTRAINT fk_anuncio_produto
        FOREIGN KEY (id_produto)
        REFERENCES produto(id_produto),

    CONSTRAINT fk_anuncio_status
        FOREIGN KEY (idstatus_anuncio)
        REFERENCES status_anuncio(idstatus_anuncio)
);


-- ============================================================
-- IMAGENS
-- ============================================================

CREATE TABLE imagem_produto (
    id_imagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INTEGER NOT NULL,
    caminho_imagem VARCHAR(255) NOT NULL,
    imagem_principal SMALLINT DEFAULT 0,

    CONSTRAINT fk_imagem_produto
        FOREIGN KEY (id_produto)
        REFERENCES produto(id_produto)
);


-- ============================================================
-- DADOS FIXOS
-- ============================================================

INSERT INTO tipo_usuario
(idtipo_usuario, tipo_usuario)
VALUES
(1, 'comprador'),
(2, 'vendedor'),
(3, 'administrador');


INSERT INTO status_usuario
(idstatus_usuario, status_usuario)
VALUES
(1, 'ativo'),
(2, 'inativo');


INSERT INTO status_loja
(idstatus_loja, status_loja)
VALUES
(1, 'Ativa'),
(2, 'Inativa');


INSERT INTO status_anuncio
(idstatus_anuncio, status_anuncio)
VALUES
(1, 'Ativo'),
(2, 'Pausado'),
(3, 'Vendido');


INSERT INTO categoria
(id_categoria, nome)
VALUES
(1, 'Eletrônicos'),
(2, 'Veículos'),
(3, 'Imóveis'),
(4, 'Moda e Vestuário'),
(5, 'Casa e Jardim'),
(6, 'Esportes e Lazer'),
(7, 'Brinquedos e Jogos'),
(8, 'Livros e Papelaria'),
(9, 'Música e Instrumentos'),
(10, 'Ferramentas e Construção'),
(11, 'Saúde e Beleza'),
(12, 'Animais de Estimação'),
(13, 'Outros');


INSERT INTO condicao_produto
(id_condicao, nome)
VALUES
(1, 'Novo'),
(2, 'Semi Novo'),
(3, 'Bom Estado'),
(4, 'Regular');


-- ============================================================
-- LOCALIZAÇÕES
-- ============================================================

INSERT INTO localizacao
(id_localizacao, cidade, estado, cep, bairro)
VALUES
(25, 'Campo Mourão', 'Paraná', '', NULL),
(29, 'Campo Mourão', 'Paraná', '', NULL),
(30, 'Campo Mourão', 'Paraná', '', NULL),
(31, 'Pato Branco', 'Paraná', '', NULL),
(32, 'Campo Mourão', 'Paraná', '', NULL),
(33, 'Campo Mourão', 'Paraná', '', NULL),
(34, 'Campo Mourão', 'Paraná', '', NULL),
(35, 'Campo Mourão', 'PR', '87303307', ''),
(36, 'Campo Mourão', 'PR', '87303307', 'Jardim São Sebastião'),
(37, 'Campo Mourão', 'PR', '87303307', 'Jardim São Sebastião'),
(38, 'Campo Mourão', 'PR', '87303307', 'Jardim São Sebastião'),
(39, 'Campo Mourão', 'PR', '87303307', 'Jardim São Sebastião'),
(40, 'Campo Mourão', 'PR', '', NULL),
(41, 'Araruna', 'PR', '', NULL),
(42, 'Araruna', 'PR', '', NULL),
(43, 'Campo Mourão', 'PR', '', NULL),
(44, 'Campo Mourão', 'PR', '', NULL),
(45, 'Campo Mourão', 'PR', '', NULL),
(46, 'Campo Mourão', 'PR', '', NULL),
(47, 'Campo Mourão', 'PR', '', NULL),
(48, 'Campo Mourão', 'PR', '', NULL),
(49, 'Pato Branco', 'PR', '', NULL),
(50, 'Pato Branco', 'PR', '', NULL);


-- ============================================================
-- USUÁRIOS
-- ============================================================

INSERT INTO usuario
(
    id_usuario,
    nome,
    cpf,
    telefone,
    email,
    senha,
    data_cadastro,
    idtipo_usuario,
    idstatus_usuario,
    id_localizacao,
    senha_resetada
)
VALUES
(
    23,
    'João',
    '097.518.929-88',
    NULL,
    'joaopedrobuhler26@gmail.com',
    '$2b$10$HyL04R84QCuhI4MKPiEVVO02rT5y2oLnIFF7vGfgwHZ/WEJsDfT9.',
    '2026-05-04 00:28:04',
    3,
    1,
    25,
    0
),
(
    30,
    'Joao bozz',
    '417.899.130-20',
    NULL,
    'joaobozz@gmail.com',
    '$2b$10$2jlkudhSdmp8ed6fP/AybevD5e0pek7fNr0SKpqcPM80q6bwDjYhW',
    '2026-05-13 17:06:57',
    1,
    1,
    32,
    0
),
(
    32,
    'João Pedro',
    '097.518.929-88',
    NULL,
    'joaopedro@gmail.com',
    '$2b$10$ZpeRDa0hFSsdxzLCui1ApeUn3tNLh7j8oyvJqjvrkfsTeNoGGK9ue',
    '2026-05-14 11:30:51',
    2,
    2,
    34,
    0
),
(
    33,
    'João Bühler',
    '16168483918',
    NULL,
    'ericklemes@gmail.com',
    '$2b$10$ZRZwttdwijgvJwpGA6GLs.8hlKxmjyOFN9QXntISLm8Jv/RM0x66y',
    '2026-07-09 11:39:32',
    2,
    1,
    40,
    0
),
(
    34,
    'João Bühler',
    '080.554.990-04',
    NULL,
    'antonio@gmail.com',
    '$2b$10$VwGLP..cHYAL/uriXYqL5es9hFcwvfMG5TApK8zNPmWuzyWNXjh.q',
    '2026-07-09 11:42:30',
    1,
    1,
    41,
    0
),
(
    35,
    'Hiago',
    '084.787.400-15',
    NULL,
    'hiago@gmail.com',
    '$2b$10$pq0ZYBXFLlrp6Q/9Rd2mIeGuvdJ48M3rKHYhhCWoHp7Skst82/emC',
    '2026-07-09 11:43:08',
    2,
    2,
    42,
    0
),
(
    37,
    'Vitor',
    '721.394.910-17',
    NULL,
    'vitor@gmail.com',
    '$2b$10$I8pYc.hLMXhRGTz4VRCxwOqcFTgi6ck9OhaGfTpuphor3aPaOvw/q',
    '2026-07-09 11:45:00',
    1,
    1,
    44,
    0
),
(
    38,
    'JOAO PEDRO BUHLER',
    '09751892988',
    NULL,
    'xynhg01@gmail.com',
    '$2b$10$H10JrM1AsPT50fREZ1VIGuTmm/FohFFOsBl6xFMgC5KCCoSLRyBgW',
    '2026-08-19 18:09:23',
    2,
    1,
    45,
    0
),
(
    41,
    'Joao',
    '09751892988',
    '46991262603',
    'pedro@gmail.com',
    '$2b$10$rfdRP5OKvgArEKKPmLHX4eIZcmOlzeT/eJkenNlUKK/.RlsUyAO5m',
    '2026-08-19 22:41:14',
    2,
    1,
    48,
    0
),
(
    43,
    'Joao Buhler',
    '09751892988',
    '46991262607',
    'joao@hotmail.com',
    '$2b$10$5bBNnuLlTtkXlvvZQNj9muqhFa5MygEc1JO58VIFTm6Be2ApVhlmW',
    '2026-08-19 23:44:25',
    1,
    1,
    50,
    0
);


-- ============================================================
-- LOJAS
-- ============================================================

INSERT INTO loja_anunciante
(
    id_loja,
    nome,
    id_usuario,
    id_localizacao,
    idstatus_loja
)
VALUES
(1, 'Loja do joão', 32, 39, 1),
(2, 'Loja de JOAO PEDRO BUHLER', 38, 45, 1),
(3, 'Loja de Joao', 41, 48, 1),
(4, 'Loja de Joao Buhler', 43, 50, 1),
(5, 'Loja de João', 23, 25, 1);


-- ============================================================
-- PRODUTOS
-- ============================================================

INSERT INTO produto
(
    id_produto,
    nome,
    descricao,
    preco,
    status,
    id_loja,
    id_categoria,
    id_condicao
)
VALUES
(1, 'Iphone13', 'topzera', '3000', 'ativo', 1, 1, 1),
(2, 'Iphone14', 'muito bom', '4000', 'ativo', 1, 1, 3),
(3, 'Cadeira', 'Cadeira ergonomica simples', '500', 'ativo', 1, 3, 1),
(4, 'mouse', 'mouse novo logitech', '100', 'ativo', 1, 1, 1),
(5, 'Cadeira', 'gamer', '200', 'ativo', 2, 11, 1),
(6, 'Celular Samsung', 'Celular s26 Ultra', '4000', 'ativo', 3, 1, 1),
(7, 'Iphone 16 128GB', 'Apple iPhone 16 (128 GB) - Rosa - Distribuidor Autorizado', '4500', 'ativo', 3, 1, 1),
(8, 'Iphone 16 128GB', 'iphone', '4000', 'ativo', 3, 1, 1),
(9, 'Iphone 16 128GB', 'iphone', '4000', 'ativo', 3, 1, 1),
(10, 'Iphone 16 128GB', 'iphone', '4000', 'ativo', 3, 1, 1),
(11, 'Iphone 16 128GB', 'iphone', '4000', 'ativo', 3, 1, 1),
(12, 'Iphone 16 128GB', 'aaaa', '22222', 'ativo', 3, 12, 2),
(13, 'Iphone 16 128GB', 'aaa', '222222', 'ativo', 4, 11, 2),
(14, 'dadasdas', 'dsadada', '32393012', 'ativo', 5, 12, 3),
(15, 'Samsung s26', 'celular', '50000', 'ativo', 5, 1, 1),
(16, 'Lanterna Ecopower 8135', 'Lanterna com por', '100', 'ativo', 5, 1, 2);


-- ============================================================
-- ANÚNCIOS
-- ============================================================

INSERT INTO anuncio
(
    id_anuncio,
    titulo,
    descricao,
    id_produto,
    idstatus_anuncio
)
VALUES
(1, 'Iphone13', 'topzera', 1, 1),
(2, 'Iphone14', 'muito bom', 2, 1),
(3, 'Cadeira', 'Cadeira ergonomica simples', 3, 1),
(4, 'mouse', 'mouse novo logitech', 4, 1),
(5, 'Cadeira', 'gamer', 5, 1),
(6, 'Celular Samsung', 'Celular s26 Ultra', 6, 1),
(7, 'Iphone 16 128GB', 'Apple iPhone 16 (128 GB) - Rosa - Distribuidor Autorizado', 7, 1),
(8, 'Iphone 16 128GB', 'iphone', 8, 1),
(9, 'Iphone 16 128GB', 'iphone', 9, 1),
(10, 'Iphone 16 128GB', 'iphone', 10, 1),
(11, 'Iphone 16 128GB', 'iphone', 11, 1),
(12, 'Iphone 16 128GB', 'aaaa', 12, 1),
(13, 'Iphone 16 128GB', 'aaa', 13, 1),
(14, 'dadasdas', 'dsadada', 14, 1),
(15, 'Samsung s26', 'celular', 15, 1),
(16, 'Lanterna Ecopower 8135', 'Lanterna com por', 16, 1);


-- ============================================================
-- IMAGENS
-- ============================================================

INSERT INTO imagem_produto
(
    id_imagem,
    id_produto,
    caminho_imagem,
    imagem_principal
)
VALUES
(1, 6, '1787181038934-219159510.jpg', 1),
(2, 7, '1787181512023-379553807.webp', 1),
(3, 8, '1787181769039-944951154.webp', 1),
(4, 9, '1787182074944-148087819.webp', 1),
(5, 10, '1787182094826-902110859.webp', 1),
(6, 11, '1787182407428-965457101.webp', 1),
(7, 12, '1787182645906-178535009.webp', 1),
(8, 13, '1787183261627-985740789.webp', 1),
(9, 14, '1787221977564-240242373.jpg', 1),
(10, 15, '1787222291778-156224237.jpg', 1),
(11, 16, '1787224443284-885184366.jpeg', 1);


-- ============================================================
-- AJUSTE DAS SEQUÊNCIAS
-- ============================================================

SELECT setval(
    pg_get_serial_sequence('categoria', 'id_categoria'),
    COALESCE((SELECT MAX(id_categoria) FROM categoria), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('condicao_produto', 'id_condicao'),
    COALESCE((SELECT MAX(id_condicao) FROM condicao_produto), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('localizacao', 'id_localizacao'),
    COALESCE((SELECT MAX(id_localizacao) FROM localizacao), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('usuario', 'id_usuario'),
    COALESCE((SELECT MAX(id_usuario) FROM usuario), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('loja_anunciante', 'id_loja'),
    COALESCE((SELECT MAX(id_loja) FROM loja_anunciante), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('produto', 'id_produto'),
    COALESCE((SELECT MAX(id_produto) FROM produto), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('anuncio', 'id_anuncio'),
    COALESCE((SELECT MAX(id_anuncio) FROM anuncio), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('imagem_produto', 'id_imagem'),
    COALESCE((SELECT MAX(id_imagem) FROM imagem_produto), 1),
    true
);


-- ============================================================
-- VERIFICAÇÃO
-- ============================================================

SELECT 'tipo_usuario' AS tabela, COUNT(*) AS registros FROM tipo_usuario
UNION ALL
SELECT 'status_usuario', COUNT(*) FROM status_usuario
UNION ALL
SELECT 'status_loja', COUNT(*) FROM status_loja
UNION ALL
SELECT 'status_anuncio', COUNT(*) FROM status_anuncio
UNION ALL
SELECT 'categoria', COUNT(*) FROM categoria
UNION ALL
SELECT 'condicao_produto', COUNT(*) FROM condicao_produto
UNION ALL
SELECT 'localizacao', COUNT(*) FROM localizacao
UNION ALL
SELECT 'usuario', COUNT(*) FROM usuario
UNION ALL
SELECT 'loja_anunciante', COUNT(*) FROM loja_anunciante
UNION ALL
SELECT 'produto', COUNT(*) FROM produto
UNION ALL
SELECT 'anuncio', COUNT(*) FROM anuncio
UNION ALL
SELECT 'imagem_produto', COUNT(*) FROM imagem_produto;

